name: "Approve failure"
description: "Approve any check no matter it's actual conclusion."
inputs:
  github_token:
    required: true
  type:
    required: true
    default: "status"
  name:
    required: true
    default: "Visual regression test"
  approve_comment:
    required: true
    default: "backstop-check approve"
runs:
  using: "node20"
  main: "dist/index.js"
