name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: "20"
      - run: npm install
      - run: npm exec eslint

  markdownlint:
    name: markdown
    runs-on: ubuntu-24.04

    steps:
    - name: Check out code
      uses: actions/checkout@v5
    - name: Run markdown lint
      uses: DavidAnson/markdownlint-cli2-action@v20
